### ISSUE TITLE
Note tempo labels are all over the staffs

### ISSUE THREAD

**Issue by KangboLu** [jeetee/MuseScore_TempoChanges#18]
I used the plugin for v3 to add ritardando to my score. The tempo label appeared on each note within the selected regions. Any ideas why this happened?

**Comment by jeetee** [comment]
You mean, no longer invisible? Because adding tempo labels to each note is exactly what this plugin does.

**Comment by KangboLu** [comment]
Okay, got it. I originally thought it will only add tempo change to the begin and end of the select notes.
