### ISSUE TITLE
Shouldn't it be a System text instead of Staff text??

### ISSUE THREAD

**Issue by BrunoVernay** [jeetee/MuseScore_TempoChanges#24]
Since the tempo change will apply to the whole system anyway.

**Comment by jeetee** [comment]
The tempo elements are, the indicative text isn't as it is not possible in the plugin framework to create system texts.

Once MuseScore allows us to create this as a system text, I will adjust the plugin accordingly

**Comment by jeetee** [comment]
See also https://musescore.org/en/node/120256 where this was first investigated/discussed.
