### ISSUE TITLE
Document how to remove the Tempo Change

### ISSUE THREAD

**Issue by BrunoVernay** [jeetee/MuseScore_TempoChanges#25]
You could add tips on how to remove the Tempo changes
(for when the Ctrl-z is too far away)

1. Select the affected measures
2. Right-clic on one of the hidden Tempo indication
3. In the popup menu, clic **Select** / **All Similar Elements in Range Selection**
4. Now, only the tempo indications for the selected measures should be selected
5. Hit Delete

There might be a more step by step version 

1. Select the affected measures
2. Right-clic on one of the hidden Tempo indication
3. Go to Select / More ...
4. Verify that the Element type is indeed "Tempo" (if not, retry step 2)
5. Check "In selection"   
6. clic OK
7. Now, only the tempo indications for the selected measures should be selected
8. Delete

**Comment by jeetee** [comment]
If I were to document it, it would likely be: See the handbook on how to remove markings.
I have no desire to document the MuseScore handbook and duplicate that information within the plugin.

To top that, the linked page from the handbook that describes the hidden marker technique doesn't document how to remove that as well. Just like it doesn't say on every page of every element that to remove it; you should select it (with a plethora of selection options) and then issue a delete command (which again has already 3 possible ways of being issued).
