### ISSUE TITLE
This plugin's dialog doesn't look good in Dark Mode

### ISSUE THREAD

**Issue by Jojo-Schmitz** [jeetee/MuseScore_TempoChanges#28]
Esp. the BPM pull down menu, when not pressed:
![image](https://user-images.githubusercontent.com/1786669/126171800-10741fc6-5fe4-48e7-9e8b-5d52fa8aa7f8.png)
The other colors are not optimal but bearable

**Comment by jeetee** [comment]
Is that also the case if you use an up to date version of the plugin instead?
ISTR some care was taken with BSG when the linear/curved option was introduced to make it work acceptable under dark mode as well.

**Comment by Jojo-Schmitz** [comment]
Hmm, that might help, lemme try...

**Comment by Jojo-Schmitz** [comment]
Outch, it does, sorry...

![image](https://user-images.githubusercontent.com/1786669/126339916-2022a66a-d3b1-453a-9e93-a53795298d71.png)
