### ISSUE TITLE
Add a humanization random option

### ISSUE THREAD

**Issue by SamuelMiller** [jeetee/MuseScore_TempoChanges#7]
How about adding a humanization option to the dialogue box  that could assign subtle random tempos to each note within a user set range based on a section's over all tempo? It would be interesting if Musescore's playback could be made to sound more human by introducing minute note tempo and velocity variations/imperfections. Thanks, Sam

**Comment by jeetee** [comment]
Whilst that would be nice I don't think this plugin would be the correct place for a humanize playback option. Perhaps someone will step up and make a humanize plugin.
In my opinion though, such an implementation would either (A) still sound mechanical if it's easy to write or (B) require something bordering on decent AI to get a good interpretation of a music piece. After all, no human interprets a piece in an identical way.

If you have the time you can always try and use the pianoroll editor as well as give each note a velocity offset value to your hearts desire inside MuseScore (I believe velocity isn't even available to the plugin framework).

But it is out of scope for this plugin.
