### ISSUE TITLE
Make compatible with MuseScore 3

### ISSUE THREAD

**Issue by jeetee** [jeetee/MuseScore_TempoChanges#8]
Currently the plugin framework for MuseScore 3 is in flux and disabled.
This issue is here to remind me to track the status of that and update as soon as possible.

It's quite likely the current version will have to be renamed in support of 2.x versions and a new copy of it modified for v3.x

**Comment by BeyondTheHorizon** [comment]
With the release of 3.0.2, the plugin framework has been reinstated, just so you know.

**Comment by RobinW99** [comment]
Thank you very much!!!

Op wo 30 jan. 2019 17:15 schreef BeyondTheHorizon <notifications@github.com:

**Comment by jeetee** [comment]
> With the release of 3.0.2, the plugin framework has been reinstated, just so you know.

Well.. mostly. But likely enough to get this working again.
I'm taking part in the FOSDEM developer meetup and updating this plugin is planned to happen during our meetup on Saturday.

Will keep you posted!

**Comment by RobinW99** [comment]
👍

Op wo 30 jan. 2019 17:52 schreef Johan Temmerman <notifications@github.com:

**Comment by jeetee** [comment]
We're not there yet guys; tested it out here at FOSDEM and talked some things through. There is still a part of the plugin framework which I need unavailable (namely the possibility to reach existing tempo texts in the score, so I can edit them and set their tempo).

Keeping a close eye on the plugin development.

**Comment by jeetee** [comment]
Just keeping you all informed; with the recent merge of https://musescore.org/en/node/283179 it looks like  the major item blocking me from updating the plugin might've been addressed for the upcoming 3.0.5 release.
To be continued…

**Comment by murphyke** [comment]
@jeetee Thanks for the update. I'm eagerly awaiting the update!

**Comment by jeetee** [comment]
See https://github.com/jeetee/MuseScore_TempoChanges/releases/tag/3.0.0 and/or https://musescore.org/en/project/tempochanges
